#!/bin/bash

echo "=== HyprExpo Functionality Test ==="
echo ""

echo "1. Plugin Status:"
echo "   - Plugin should be loaded in Hyprland"
echo "   - Check with: hyprctl plugins"
echo ""

echo "2. Available Commands:"
echo "   - hyprctl dispatch hyprexpo:expo toggle    # Toggle overview"
echo "   - hyprctl dispatch hyprexpo:expo select    # Select workspace"
echo "   - hyprctl dispatch hyprexpo:expo off       # Close overview"
echo "   - hyprctl dispatch hyprexpo:expo close     # Close overview"
echo "   - hyprctl dispatch hyprexpo:expo disable   # Close overview"
echo ""

echo "3. Gesture Support:"
echo "   - 4-finger vertical swipe to activate"
echo "   - Configured in plugin settings"
echo ""

echo "4. Configuration Options:"
echo "   - plugin:hyprexpo:columns (default: 3)"
echo "   - plugin:hyprexpo:gap_size (default: 5)"
echo "   - plugin:hyprexpo:enable_gesture (default: 1)"
echo "   - plugin:hyprexpo:gesture_fingers (default: 4)"
echo ""

echo "5. Testing Steps:"
echo "   a) Try: hyprctl dispatch hyprexpo:expo toggle"
echo "   b) Try: 4-finger vertical swipe gesture"
echo "   c) Check for notifications when plugin loads"
echo ""

echo "6. Debug Information:"
echo "   - Check Hyprland logs for plugin messages"
echo "   - Look for '[hyprexpo]' notifications"
echo ""

echo "=== Test Commands ==="
echo "Run these commands to test:"
echo ""
echo "# Test toggle command"
echo "hyprctl dispatch hyprexpo:expo toggle"
echo ""
echo "# Check plugin status"
echo "hyprctl plugins | grep hyprexpo"
echo ""
echo "# Check configuration"
echo "hyprctl getoption plugin:hyprexpo:columns"
echo "hyprctl getoption plugin:hyprexpo:enable_gesture"
